cc_library(
    name = "poller",
    srcs = [
        "poller.cpp",
        ],
    hdrs = [
        "base.h",
        "poller.h",
        ],
    visibility = ["//visibility:public"],
    copts = [
        "-std=c++20",
        ],
    deps = [
        # 这里可以添加你的依赖项
    ],
)
